# Generated by Django 5.2.15 on 2026-07-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EntidadInstitucional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_oficial", models.CharField(max_length=50, unique=True)),
                ("nombre", models.CharField(max_length=200, unique=True)),
                ("subsector", models.CharField(max_length=150)),
                ("nivel_gobierno", models.CharField(max_length=100)),
                (
                    "estado",
                    models.CharField(
                        choices=[("ACTIVA", "Activa"), ("INACTIVA", "Inactiva")],
                        db_index=True,
                        default="ACTIVA",
                        max_length=10,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Entidad institucional",
                "verbose_name_plural": "Entidades institucionales",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="UnidadOrganizacional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("codigo", models.CharField(blank=True, max_length=50)),
                (
                    "estado",
                    models.CharField(
                        choices=[("ACTIVA", "Activa"), ("INACTIVA", "Inactiva")],
                        db_index=True,
                        default="ACTIVA",
                        max_length=10,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "entidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unidades",
                        to="configuracion.entidadinstitucional",
                    ),
                ),
                (
                    "unidad_padre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subunidades",
                        to="configuracion.unidadorganizacional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unidad organizacional",
                "verbose_name_plural": "Unidades organizacionales",
                "ordering": ["entidad__nombre", "nombre"],
            },
        ),
        migrations.AddConstraint(
            model_name="unidadorganizacional",
            constraint=models.UniqueConstraint(
                fields=("entidad", "nombre"),
                name="unique_unidad_nombre_por_entidad",
            ),
        ),
        migrations.AddConstraint(
            model_name="unidadorganizacional",
            constraint=models.UniqueConstraint(
                condition=~models.Q(("codigo", "")),
                fields=("entidad", "codigo"),
                name="unique_unidad_codigo_por_entidad",
            ),
        ),
    ]
