# Generated by Django 5.2.15 on 2026-07-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0002_plan_creado_por_plan_entidad_alter_plan_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En revisión'), ('EN_REVISION_INICIADA', 'Revisión iniciada'), ('APROBADO', 'Aprobado'), ('DEVUELTO', 'Devuelto'), ('RECHAZADO', 'Rechazado'), ('ARCHIVADO', 'Archivado')], default='BORRADOR', max_length=20),
        ),
    ]
