# Generated by Django 5.2.15 on 2026-07-13 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0003_alter_plan_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEstadoPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=40)),
                ('estado_anterior', models.CharField(max_length=30)),
                ('estado_nuevo', models.CharField(max_length=30)),
                ('observacion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_estados', to='planes.plan')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transiciones_planes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de estado de plan',
                'verbose_name_plural': 'Historiales de estado de planes',
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['plan', 'fecha'], name='planes_hist_plan_id_c3fbe5_idx')],
            },
        ),
    ]
