# Generated by Django 5.2.15 on 2026-07-26 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def reconstruir_trazabilidad_revision(apps, schema_editor):
    Plan = apps.get_model("planes", "Plan")
    Historial = apps.get_model("planes", "HistorialEstadoPlan")

    for plan in Plan.objects.all().iterator():
        eventos = Historial.objects.filter(plan_id=plan.pk)
        envio = eventos.filter(accion="ENVIAR_REVISION").order_by(
            "-fecha", "-pk"
        ).first()
        inicio = eventos.filter(accion="INICIAR_REVISION").order_by(
            "-fecha", "-pk"
        ).first()
        aprobacion = eventos.filter(accion="APROBAR").order_by(
            "-fecha", "-pk"
        ).first()

        cambios = {}
        if envio is not None:
            cambios["fecha_envio_revision"] = envio.fecha
        if plan.estado in {"EN_REVISION_INICIADA", "APROBADO"} and inicio:
            cambios["revisor_id"] = inicio.usuario_id
            cambios["fecha_inicio_revision"] = inicio.fecha
        if plan.estado == "APROBADO" and aprobacion:
            cambios["aprobado_por_id"] = aprobacion.usuario_id
            cambios["fecha_aprobacion"] = aprobacion.fecha

        if cambios:
            Plan.objects.filter(pk=plan.pk).update(**cambios)


def limpiar_trazabilidad_revision(apps, schema_editor):
    Plan = apps.get_model("planes", "Plan")
    Plan.objects.update(
        aprobado_por_id=None,
        fecha_aprobacion=None,
        fecha_envio_revision=None,
        fecha_inicio_revision=None,
        revisor_id=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
        ('metas', '0005_avanceindicador_evidencia_indicador_ponderacion_and_more'),
        ('objetivos', '0001_initial'),
        ('planes', '0004_historialestadoplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planes_aprobados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plan',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='fecha_envio_revision',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='fecha_inicio_revision',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='objetivos_estrategicos',
            field=models.ManyToManyField(blank=True, related_name='planes', through='metas.Meta', to='objetivos.objetivoestrategico'),
        ),
        migrations.AddField(
            model_name='plan',
            name='revisor',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planes_revisados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            reconstruir_trazabilidad_revision,
            limpiar_trazabilidad_revision,
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(condition=models.Q(('periodo_fin__gte', models.F('periodo_inicio'))), name='plan_rango_fechas_valido'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('fecha_inicio_revision__isnull', True), ('revisor__isnull', True)), models.Q(('fecha_inicio_revision__isnull', False), ('revisor__isnull', False)), _connector='OR'), name='plan_revisor_fecha_coherentes'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('aprobado_por__isnull', True), ('fecha_aprobacion__isnull', True)), models.Q(('aprobado_por__isnull', False), ('fecha_aprobacion__isnull', False)), _connector='OR'), name='plan_aprobador_fecha_coherentes'),
        ),
    ]
