# Generated by Django 5.2.15 on 2026-07-12

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("configuracion", "0001_initial"),
        ("objetivos", "0001_initial"),
        ("planes", "0002_plan_creado_por_plan_entidad_alter_plan_nombre_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TipologiaIntervencion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50)),
                ("nombre", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tipología de intervención",
                "verbose_name_plural": "Tipologías de intervención",
                "ordering": ["nombre", "codigo"],
            },
        ),
        migrations.CreateModel(
            name="ProyectoInversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50)),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                (
                    "presupuesto_estimado",
                    models.DecimalField(decimal_places=2, max_digits=16),
                ),
                (
                    "avance_fisico",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.00"),
                                "El porcentaje no puede ser negativo.",
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("100.00"),
                                "El porcentaje no puede superar el 100%.",
                            ),
                        ],
                    ),
                ),
                (
                    "avance_financiero",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.00"),
                                "El porcentaje no puede ser negativo.",
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("100.00"),
                                "El porcentaje no puede superar el 100%.",
                            ),
                        ],
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("PLANIFICADO", "Planificado"),
                            ("EN_REVISION", "En revisión"),
                            ("APROBADO", "Aprobado"),
                            ("EN_EJECUCION", "En ejecución"),
                            ("SUSPENDIDO", "Suspendido"),
                            ("FINALIZADO", "Finalizado"),
                            ("ARCHIVADO", "Archivado"),
                        ],
                        default="BORRADOR",
                        max_length=20,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proyectos_inversion_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proyectos_inversion",
                        to="configuracion.entidadinstitucional",
                    ),
                ),
                (
                    "objetivo_estrategico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proyectos_inversion",
                        to="objetivos.objetivoestrategico",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proyectos_inversion",
                        to="planes.plan",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proyectos_inversion_responsables",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tipologia_intervencion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proyectos",
                        to="proyectos.tipologiaintervencion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proyecto de inversión",
                "verbose_name_plural": "Proyectos de inversión",
                "ordering": ["-fecha_creacion", "codigo"],
            },
        ),
        migrations.CreateModel(
            name="HitoProyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.PositiveIntegerField()),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("fecha_inicio_planificada", models.DateField()),
                ("fecha_fin_planificada", models.DateField()),
                (
                    "porcentaje_planificado",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.00"),
                                "El porcentaje no puede ser negativo.",
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("100.00"),
                                "El porcentaje no puede superar el 100%.",
                            ),
                        ],
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hitos",
                        to="proyectos.proyectoinversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hito de proyecto",
                "verbose_name_plural": "Hitos de proyecto",
                "ordering": ["proyecto", "orden"],
            },
        ),
        migrations.CreateModel(
            name="SeguimientoProyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "avance_fisico",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.00"),
                                "El porcentaje no puede ser negativo.",
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("100.00"),
                                "El porcentaje no puede superar el 100%.",
                            ),
                        ],
                    ),
                ),
                (
                    "avance_financiero",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.00"),
                                "El porcentaje no puede ser negativo.",
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("100.00"),
                                "El porcentaje no puede superar el 100%.",
                            ),
                        ],
                    ),
                ),
                ("observacion", models.TextField(blank=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "hito",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="seguimientos",
                        to="proyectos.hitoproyecto",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="seguimientos",
                        to="proyectos.proyectoinversion",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="seguimientos_proyectos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Seguimiento de proyecto",
                "verbose_name_plural": "Seguimientos de proyectos",
                "ordering": ["-fecha_registro", "-fecha_creacion"],
            },
        ),
        migrations.AddConstraint(
            model_name="tipologiaintervencion",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("codigo"),
                name="uniq_tipologia_intervencion_codigo_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="tipologiaintervencion",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("nombre"),
                name="uniq_tipologia_intervencion_nombre_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="proyectoinversion",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("codigo"),
                models.F("entidad"),
                name="uniq_proyecto_entidad_codigo_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="proyectoinversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("presupuesto_estimado__gte", 0)),
                name="ck_proyecto_presupuesto_no_negativo",
            ),
        ),
        migrations.AddConstraint(
            model_name="proyectoinversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("fecha_fin__gte", models.F("fecha_inicio"))),
                name="ck_proyecto_rango_fechas_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="proyectoinversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("avance_fisico__gte", 0), ("avance_fisico__lte", 100)
                ),
                name="ck_proyecto_avance_fisico",
            ),
        ),
        migrations.AddConstraint(
            model_name="proyectoinversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("avance_financiero__gte", 0),
                    ("avance_financiero__lte", 100),
                ),
                name="ck_proyecto_avance_financiero",
            ),
        ),
        migrations.AddConstraint(
            model_name="proyectoinversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "estado__in",
                        [
                            "BORRADOR",
                            "PLANIFICADO",
                            "EN_REVISION",
                            "APROBADO",
                            "EN_EJECUCION",
                            "SUSPENDIDO",
                            "FINALIZADO",
                            "ARCHIVADO",
                        ],
                    )
                ),
                name="ck_proyecto_estado",
            ),
        ),
        migrations.AddConstraint(
            model_name="hitoproyecto",
            constraint=models.UniqueConstraint(
                fields=("proyecto", "orden"),
                name="uniq_hito_proyecto_orden",
            ),
        ),
        migrations.AddConstraint(
            model_name="hitoproyecto",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("nombre"),
                models.F("proyecto"),
                name="uniq_hito_proyecto_nombre_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="hitoproyecto",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "fecha_fin_planificada__gte",
                        models.F("fecha_inicio_planificada"),
                    )
                ),
                name="ck_hito_rango_fechas_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="hitoproyecto",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("porcentaje_planificado__gte", 0),
                    ("porcentaje_planificado__lte", 100),
                ),
                name="ck_hito_porcentaje_planificado",
            ),
        ),
        migrations.AddConstraint(
            model_name="seguimientoproyecto",
            constraint=models.UniqueConstraint(
                fields=("proyecto", "fecha_registro"),
                name="uniq_seguimiento_proyecto_fecha",
            ),
        ),
        migrations.AddConstraint(
            model_name="seguimientoproyecto",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("avance_fisico__gte", 0), ("avance_fisico__lte", 100)
                ),
                name="ck_seguimiento_avance_fisico",
            ),
        ),
        migrations.AddConstraint(
            model_name="seguimientoproyecto",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("avance_financiero__gte", 0),
                    ("avance_financiero__lte", 100),
                ),
                name="ck_seguimiento_avance_financiero",
            ),
        ),
    ]
