# Generated by Django 5.2.15 on 2026-07-12 15:50

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EjePND',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], db_index=True, default='ACTIVO', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Eje PND',
                'verbose_name_plural': 'Ejes PND',
                'ordering': ['codigo'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('codigo'), name='uniq_eje_pnd_codigo_ci'), models.CheckConstraint(condition=models.Q(('estado__in', ['ACTIVO', 'INACTIVO'])), name='ck_eje_pnd_estado')],
            },
        ),
        migrations.CreateModel(
            name='ObjetivoEstrategico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], db_index=True, default='ACTIVO', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objetivos_estrategicos', to='configuracion.entidadinstitucional')),
            ],
            options={
                'verbose_name': 'Objetivo estratégico institucional',
                'verbose_name_plural': 'Objetivos estratégicos institucionales',
                'ordering': ['entidad__nombre', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='ObjetivoPND',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], db_index=True, default='ACTIVO', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('eje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objetivos', to='objetivos.ejepnd')),
            ],
            options={
                'verbose_name': 'Objetivo PND',
                'verbose_name_plural': 'Objetivos PND',
                'ordering': ['eje__codigo', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='ODS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1, 'El número del ODS debe ser positivo.')])),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], db_index=True, default='ACTIVO', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ODS',
                'verbose_name_plural': 'ODS',
                'ordering': ['numero'],
                'constraints': [models.CheckConstraint(condition=models.Q(('numero__gte', 1)), name='ck_ods_numero_positivo'), models.CheckConstraint(condition=models.Q(('estado__in', ['ACTIVO', 'INACTIVO'])), name='ck_ods_estado')],
            },
        ),
        migrations.CreateModel(
            name='Alineacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificacion', models.TextField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('VALIDADA', 'Validada'), ('RECHAZADA', 'Rechazada')], db_index=True, default='BORRADOR', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alineaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_validador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alineaciones_validadas', to=settings.AUTH_USER_MODEL)),
                ('objetivo_estrategico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alineaciones', to='objetivos.objetivoestrategico')),
                ('objetivo_pnd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alineaciones', to='objetivos.objetivopnd')),
                ('ods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alineaciones', to='objetivos.ods')),
            ],
            options={
                'verbose_name': 'Alineación de objetivo',
                'verbose_name_plural': 'Alineaciones de objetivos',
                'ordering': ['-fecha_actualizacion', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='objetivoestrategico',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('codigo'), models.F('entidad'), name='uniq_obj_estrategico_entidad_codigo_ci'),
        ),
        migrations.AddConstraint(
            model_name='objetivoestrategico',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['ACTIVO', 'INACTIVO'])), name='ck_obj_estrategico_estado'),
        ),
        migrations.AddConstraint(
            model_name='objetivopnd',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('codigo'), models.F('eje'), name='uniq_obj_pnd_eje_codigo_ci'),
        ),
        migrations.AddConstraint(
            model_name='objetivopnd',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['ACTIVO', 'INACTIVO'])), name='ck_obj_pnd_estado'),
        ),
        migrations.AddConstraint(
            model_name='alineacion',
            constraint=models.UniqueConstraint(fields=('objetivo_estrategico', 'objetivo_pnd', 'ods'), name='uniq_alineacion_obj_pnd_ods'),
        ),
        migrations.AddConstraint(
            model_name='alineacion',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['BORRADOR', 'VALIDADA', 'RECHAZADA'])), name='ck_alineacion_estado'),
        ),
        migrations.AddConstraint(
            model_name='alineacion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'BORRADOR'), ('usuario_validador__isnull', True)), models.Q(('estado__in', ['VALIDADA', 'RECHAZADA']), ('usuario_validador__isnull', False)), _connector='OR'), name='ck_alineacion_validador_estado'),
        ),
    ]
