# Generated by Django 5.2.15 on 2026-07-12 06:43

from django.db import migrations, models


CATALOGO_HISTORICO = [
    "usuarios.ver",
    "usuarios.crear",
    "usuarios.editar",
    "usuarios.eliminar",
    "roles.ver",
    "roles.crear",
    "roles.editar",
    "roles.eliminar",
    "roles.asignar_permisos",
    "planes.ver",
    "planes.crear",
    "planes.editar",
    "planes.eliminar",
    "planes.enviar_revision",
    "planes.revisar",
    "planes.devolver",
    "planes.aprobar",
    "planes.rechazar",
    "planes.archivar",
    "metas.ver",
    "metas.crear",
    "metas.editar",
    "metas.eliminar",
    "metas.archivar",
    "indicadores.ver",
    "indicadores.crear",
    "indicadores.editar",
    "indicadores.eliminar",
    "indicadores.registrar_avance",
    "indicadores.validar",
    "configuracion.ver",
    "configuracion.gestionar",
    "objetivos.ver",
    "objetivos.gestionar",
    "alineaciones.ver",
    "alineaciones.gestionar_catalogos",
    "alineaciones.gestionar",
    "alineaciones.validar",
    "proyectos.ver",
    "proyectos.crear",
    "proyectos.editar",
    "proyectos.eliminar",
    "proyectos.enviar_revision",
    "proyectos.devolver",
    "proyectos.aprobar",
    "proyectos.archivar",
    "proyectos.registrar_seguimiento",
    "proyectos.gestionar_catalogos",
    "reportes.ver",
    "reportes.exportar",
    "auditoria.ver",
    "auditoria.exportar",
]


def _ordenar(codigos):
    incluidos = set(codigos)
    return [codigo for codigo in CATALOGO_HISTORICO if codigo in incluidos]


ROLES_BASE_HISTORICOS = {
    "administrador_sistema": {
        "nombre": "Administrador del Sistema",
        "descripcion": "Administra usuarios, roles y configuración institucional.",
        "permisos": _ordenar(
            {
                "usuarios.ver", "usuarios.crear", "usuarios.editar",
                "usuarios.eliminar", "roles.ver", "roles.crear",
                "roles.editar", "roles.eliminar", "roles.asignar_permisos",
                "planes.ver", "metas.ver", "indicadores.ver",
                "configuracion.ver", "configuracion.gestionar",
                "objetivos.ver", "alineaciones.ver",
                "alineaciones.gestionar_catalogos", "proyectos.ver",
                "proyectos.gestionar_catalogos", "reportes.ver",
                "reportes.exportar", "auditoria.ver",
            }
        ),
    },
    "planificador_institucional": {
        "nombre": "Planificador Institucional",
        "descripcion": "Gestiona la planificación y el seguimiento institucional.",
        "permisos": _ordenar(
            {
                "usuarios.ver", "configuracion.ver", "planes.ver",
                "planes.crear", "planes.editar", "planes.enviar_revision",
                "planes.archivar", "metas.ver", "metas.crear",
                "metas.editar", "metas.archivar", "indicadores.ver",
                "indicadores.crear", "indicadores.editar",
                "indicadores.registrar_avance", "objetivos.ver",
                "objetivos.gestionar", "alineaciones.ver",
                "alineaciones.gestionar", "proyectos.ver",
                "proyectos.crear", "proyectos.editar",
                "proyectos.enviar_revision", "proyectos.archivar",
                "proyectos.registrar_seguimiento", "reportes.ver",
                "reportes.exportar",
            }
        ),
    },
    "supervisor_planificacion": {
        "nombre": "Supervisor de Planificación",
        "descripcion": "Revisa, devuelve, aprueba y rechaza planificación.",
        "permisos": _ordenar(
            {
                "configuracion.ver", "planes.ver", "planes.revisar",
                "planes.devolver", "planes.aprobar", "planes.rechazar",
                "metas.ver", "indicadores.ver", "indicadores.validar",
                "objetivos.ver", "alineaciones.ver", "alineaciones.validar",
                "proyectos.ver", "proyectos.devolver", "proyectos.aprobar",
                "reportes.ver",
            }
        ),
    },
    "usuario_externo": {
        "nombre": "Usuario Externo",
        "descripcion": "Gestiona planificación propia dentro de su institución.",
        "permisos": _ordenar(
            {
                "configuracion.ver", "planes.ver", "planes.crear",
                "planes.editar", "planes.enviar_revision", "planes.archivar",
                "metas.ver", "metas.crear", "metas.editar", "metas.archivar",
                "indicadores.ver", "indicadores.crear", "indicadores.editar",
                "indicadores.registrar_avance", "objetivos.ver",
                "alineaciones.ver", "proyectos.ver", "proyectos.crear",
                "proyectos.editar", "proyectos.enviar_revision",
                "proyectos.archivar", "proyectos.registrar_seguimiento",
                "reportes.ver", "reportes.exportar",
            }
        ),
    },
    "auditor_control_interno": {
        "nombre": "Auditor / Control Interno",
        "descripcion": "Consulta trazabilidad y reportes sin mutaciones operativas.",
        "permisos": _ordenar(
            {
                "usuarios.ver", "roles.ver", "configuracion.ver",
                "planes.ver", "metas.ver", "indicadores.ver",
                "objetivos.ver", "alineaciones.ver", "proyectos.ver",
                "reportes.ver", "reportes.exportar", "auditoria.ver",
                "auditoria.exportar",
            }
        ),
    },
    "superadministrador_tecnico": {
        "nombre": "Superadministrador técnico",
        "descripcion": "Acceso técnico total y excepcional.",
        "permisos": list(CATALOGO_HISTORICO),
    },
}


def inicializar_roles_base(apps, schema_editor):
    Rol = apps.get_model("roles", "Rol")

    for codigo, definicion in ROLES_BASE_HISTORICOS.items():
        rol = Rol.objects.filter(codigo=codigo).first()
        if rol is None:
            rol = Rol.objects.filter(nombre__iexact=definicion["nombre"]).first()
        if rol is None and codigo == "administrador_sistema":
            rol = Rol.objects.filter(nombre__iexact="Administrador").first()
        if rol is None:
            rol = Rol(codigo=codigo)

        rol.codigo = codigo
        rol.nombre = definicion["nombre"]
        rol.descripcion = definicion["descripcion"]
        rol.activo = True
        rol.permisos = list(definicion["permisos"])
        rol.save()


class Migration(migrations.Migration):
    dependencies = [
        ("roles", "0002_rol_permisos"),
    ]

    operations = [
        migrations.AddField(
            model_name="rol",
            name="codigo",
            field=models.SlugField(
                blank=True,
                editable=False,
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.RunPython(
            inicializar_roles_base,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
