# Generated by Django 5.2.15 on 2026-07-12 22:47

from django.db import migrations, models


ALCANCES_HISTORICOS = {
    "administrador_sistema": "GLOBAL",
    "planificador_institucional": "PROPIO_ASIGNADO",
    "supervisor_planificacion": "REVISION_ENTIDAD",
    "usuario_externo": "ENTIDAD",
    "auditor_control_interno": "LECTURA_ENTIDAD",
    "superadministrador_tecnico": "TOTAL",
}


def asignar_alcances_historicos(apps, schema_editor):
    Rol = apps.get_model("roles", "Rol")
    for codigo, alcance in ALCANCES_HISTORICOS.items():
        Rol.objects.filter(codigo=codigo).update(alcance=alcance)


def revertir_alcances_historicos(apps, schema_editor):
    Rol = apps.get_model("roles", "Rol")
    Rol.objects.filter(codigo__in=ALCANCES_HISTORICOS).update(alcance="ENTIDAD")


class Migration(migrations.Migration):
    dependencies = [
        ("roles", "0003_rol_codigo"),
    ]

    operations = [
        migrations.AddField(
            model_name="rol",
            name="alcance",
            field=models.CharField(
                choices=[
                    ("TOTAL", "Total"),
                    ("GLOBAL", "Global administrativo"),
                    ("ENTIDAD", "Institución asignada"),
                    ("PROPIO_ASIGNADO", "Propios y asignados"),
                    ("REVISION_ENTIDAD", "Revisión institucional"),
                    ("LECTURA_ENTIDAD", "Lectura institucional"),
                ],
                default="ENTIDAD",
                max_length=30,
            ),
        ),
        migrations.RunPython(
            asignar_alcances_historicos,
            revertir_alcances_historicos,
        ),
    ]
