# Generated by Django 5.2 on 2026-07-08 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('valor_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_meta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('frecuencia', models.CharField(choices=[('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], default='TRIMESTRAL', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='AvanceIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='avances_indicadores', to=settings.AUTH_USER_MODEL)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avances', to='metas.indicador')),
            ],
            options={
                'verbose_name': 'Avance de indicador',
                'verbose_name_plural': 'Avances de indicadores',
                'ordering': ['-fecha_registro', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('resultado_esperado', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ACTIVA', 'Activa'), ('CERRADA', 'Cerrada'), ('ARCHIVADA', 'Archivada')], default='BORRADOR', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metas', to='planes.plan')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='indicador',
            name='meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicadores', to='metas.meta'),
        ),
        migrations.AddConstraint(
            model_name='meta',
            constraint=models.UniqueConstraint(fields=('plan', 'nombre'), name='unique_meta_por_plan'),
        ),
        migrations.AddConstraint(
            model_name='indicador',
            constraint=models.UniqueConstraint(fields=('meta', 'nombre'), name='unique_indicador_por_meta'),
        ),
    ]
