# Generated by Django 5.2.15 on 2026-07-12 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def normalizar_estado_activo_meta(apps, schema_editor):
    Meta = apps.get_model("metas", "Meta")
    Meta.objects.filter(estado="ACTIVA").update(activa=True)
    Meta.objects.exclude(estado="ACTIVA").update(activa=False)


def revertir_estado_activo_meta(apps, schema_editor):
    Meta = apps.get_model("metas", "Meta")
    Meta.objects.all().update(activa=True)


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='fecha_validacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicador',
            name='validado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='indicador',
            name='validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicadores_validados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            normalizar_estado_activo_meta,
            revertir_estado_activo_meta,
        ),
        migrations.AlterField(
            model_name='meta',
            name='activa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='meta',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(estado='ACTIVA', activa=True)
                    | models.Q(
                        estado__in=['BORRADOR', 'CERRADA', 'ARCHIVADA'],
                        activa=False,
                    )
                ),
                name='meta_estado_activa_coherente',
            ),
        ),
    ]
