# Generated by Django 5.2.15 on 2026-07-21

import django.db.models.deletion
from django.db import migrations, models


def vincular_objetivo_unico_por_entidad(apps, schema_editor):
    """Relaciona datos históricos solo cuando la elección no es ambigua."""

    Meta = apps.get_model("metas", "Meta")
    ObjetivoEstrategico = apps.get_model("objetivos", "ObjetivoEstrategico")

    for meta in Meta.objects.select_related("plan").filter(
        objetivo_estrategico__isnull=True
    ):
        activos = list(
            ObjetivoEstrategico.objects.filter(
                entidad_id=meta.plan.entidad_id,
                estado="ACTIVO",
            )
            .order_by("id")
            .values_list("id", flat=True)[:2]
        )
        if len(activos) == 1:
            Meta.objects.filter(pk=meta.pk).update(
                objetivo_estrategico_id=activos[0]
            )


class Migration(migrations.Migration):

    dependencies = [
        ("metas", "0002_indicador_fecha_validacion_indicador_validado_and_more"),
        ("objetivos", "0001_initial"),
        ("planes", "0002_plan_creado_por_plan_entidad_alter_plan_nombre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meta",
            name="objetivo_estrategico",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="metas",
                to="objetivos.objetivoestrategico",
            ),
        ),
        migrations.RunPython(
            vincular_objetivo_unico_por_entidad,
            migrations.RunPython.noop,
        ),
    ]
