# Generated by Django 5.2.15 on 2026-07-21

import django.db.models.deletion
from django.db import migrations, models


def verificar_metas_vinculadas(apps, schema_editor):
    """Detiene la migración antes de imponer la restricción si falta una relación."""

    Meta = apps.get_model("metas", "Meta")
    pendientes = Meta.objects.filter(objetivo_estrategico__isnull=True).count()
    if pendientes:
        raise RuntimeError(
            "No se puede exigir el objetivo estratégico: "
            f"existen {pendientes} meta(s) sin una relación inequívoca. "
            "Vincule esas metas con un objetivo de su entidad y reintente la migración."
        )


class Migration(migrations.Migration):

    dependencies = [
        ("metas", "0003_meta_objetivo_estrategico"),
    ]

    operations = [
        migrations.RunPython(
            verificar_metas_vinculadas,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="meta",
            name="objetivo_estrategico",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="metas",
                to="objetivos.objetivoestrategico",
            ),
        ),
    ]
