# Generated by Django 5.2.15 on 2026-07-26 04:49

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def inferir_sentido_indicadores_historicos(apps, schema_editor):
    """Congela la inferencia necesaria antes de aplicar restricciones nuevas."""

    Indicador = apps.get_model("metas", "Indicador")
    Indicador.objects.filter(
        valor_meta__lt=models.F("valor_base"),
    ).update(sentido="DESCENDENTE")
    Indicador.objects.filter(
        valor_meta__gte=models.F("valor_base"),
    ).update(sentido="ASCENDENTE")


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0004_exigir_objetivo_estrategico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='avanceindicador',
            name='evidencia',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='indicador',
            name='ponderacion',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), 'La ponderación debe ser mayor que cero.'), django.core.validators.MaxValueValidator(Decimal('100.00'), 'La ponderación no puede superar 100.')]),
        ),
        migrations.AddField(
            model_name='indicador',
            name='sentido',
            field=models.CharField(choices=[('ASCENDENTE', 'Ascendente'), ('DESCENDENTE', 'Descendente')], default='ASCENDENTE', max_length=20),
        ),
        migrations.RunPython(
            inferir_sentido_indicadores_historicos,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='avanceindicador',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gte', 0)), name='avance_indicador_valor_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='indicador',
            constraint=models.CheckConstraint(condition=models.Q(('valor_base__gte', 0)), name='indicador_valor_base_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='indicador',
            constraint=models.CheckConstraint(condition=models.Q(('valor_meta__gte', 0)), name='indicador_valor_meta_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='indicador',
            constraint=models.CheckConstraint(condition=models.Q(('valor_actual__gte', 0)), name='indicador_valor_actual_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='indicador',
            constraint=models.CheckConstraint(condition=models.Q(('ponderacion__gt', 0), ('ponderacion__lte', 100)), name='indicador_ponderacion_valida'),
        ),
        migrations.AddConstraint(
            model_name='indicador',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('sentido', 'ASCENDENTE'), ('valor_meta__gte', models.F('valor_base'))), models.Q(('sentido', 'DESCENDENTE'), ('valor_meta__lt', models.F('valor_base'))), _connector='OR'), name='indicador_sentido_valores_coherentes'),
        ),
        migrations.AddConstraint(
            model_name='indicador',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('fecha_validacion__isnull', True), ('validado', False), ('validado_por__isnull', True)), models.Q(('fecha_validacion__isnull', False), ('validado', True), ('validado_por__isnull', False)), _connector='OR'), name='indicador_validacion_coherente'),
        ),
    ]
