# Generated by Django 5.2.15 on 2026-07-12 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_identificador', models.CharField(blank=True, max_length=150)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modulo', models.CharField(db_index=True, max_length=60)),
                ('funcionalidad', models.CharField(max_length=120)),
                ('accion', models.CharField(db_index=True, max_length=60)),
                ('tipo_entidad', models.CharField(blank=True, max_length=120)),
                ('registro_id', models.CharField(blank=True, max_length=64)),
                ('valores_anteriores', models.JSONField(blank=True, default=dict)),
                ('valores_posteriores', models.JSONField(blank=True, default=dict)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('resultado', models.CharField(choices=[('EXITO', 'Éxito'), ('FALLO', 'Fallo')], db_index=True, default='EXITO', max_length=10)),
                ('detalle', models.TextField(blank=True)),
                ('entidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_auditoria', to='configuracion.entidadinstitucional')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de auditoría',
                'verbose_name_plural': 'Eventos de auditoría',
                'ordering': ['-fecha_hora', '-id'],
                'indexes': [models.Index(fields=['modulo', 'accion', 'fecha_hora'], name='auditoria_e_modulo_715833_idx'), models.Index(fields=['entidad', 'fecha_hora'], name='auditoria_e_entidad_df8072_idx')],
            },
        ),
    ]
